### ISSUE TITLE
HttpProxy Transfer: Provider Control Plane spams Consumer Control Plane + HttpProxy Backend Application with requests

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#1840] opened 2022-08-17 10:05 UTC
# Bug Report

## Describe the Bug

When the Consumer Control Plane and HttpProxy Backend Application* are not able to do a data transfer, the Provider sends a large number of requests to the Consumer Control Plane, which are forwarded to the Backend Application.

In my setup the Consumer Control Plane + Backend Application is maybe not correctly set up. But there are probably other possibilities to create this behavior, too.

*_HttpProxy Backend Application is the application, the control plane sends the tokens to, for a HttpProxy transfer._

### Expected Behavior

- When the provider sees, that the consumer can not process the requests, it should stop at some point. Currently the messages a send in a loop without or very little delay.
- When a transfer process is already completed on consumer side, it should stop sending tokens to the HttpProxy Backend Application.

### Observed Behavior

- Provider never stops sending tokens to the Consumer.
- Consumer should not accept tokens for an already finished transfer.

## Steps to Reproduce
1. Setup Provider and Consumer Connector
2. Create HttpData Offer on Provider
3. Initiate HttpProxy Transfer on Consumer
4. Setup a HttpProxy Backend Application, that causes a 503 on consumer side (or fake it)

## Context Information

- Used version 0.0.1-20220815-SNAPSHOT

## Detailed Description

Some observations:

- The loop without delay is caused by the `StateMachineManager.performLogic()`. It will always find the same transfer process, send out a request, but won't advance its state.
```java
private long performLogic() {
        try {
            var processed = processors.stream()
                    .mapToLong(StateProcessor::process)
                    .sum();

            waitStrategy.success();

            if (processed == 0) {
                return waitStrategy.waitForMillis();
            }
        } catch (Error e) {
            active.set(false);
            monitor.severe(format("StateMachineManager [%s] unrecoverable error", name), e);
        } catch (Throwable e) {
            monitor.severe(format("StateMachineManager [%s] error caught", name), e);
            return waitStrategy.retryInMillis();
        }
        return 0;
    }
```

- The Provider will spam it's logs with
```java
[2022-08-16 19:27:07] [FINE   ] Response received from connector. Status 503
[2022-08-16 19:27:07] [SEVERE ] Error processing transfer request. Setting to retry: bb811841-d230-4d91-a42d-e0d12b2a89af
```

- The consumer won't log anything, but is creating a new message to the Backend Application for each provider request. I saw this in our Backend Application logs.

- On my machine the provider send out 1326 messages to the consumer in 30 seconds. I got the number by checking the `state_count` column of the transfer process.

- The 503 on consumer side is created by throwing an exception and not using the future of `HttpEndpointDataReferenceReceiver.send()`.
```java
 @Override
    public CompletableFuture<Result<Void>> send(@NotNull EndpointDataReference edr) {
        var requestBody = RequestBody.create(typeManager.writeValueAsString(edr), JSON);
        var requestBuilder = new Request.Builder().url(endpoint).post(requestBody);
        if (!isNullOrBlank(authKey) && !isNullOrBlank(authToken)) {
            requestBuilder.header(authKey, authToken);
        }
        try (var response = with(retryPolicy).get(() -> httpClient.newCall(requestBuilder.build()).execute())) {
            if (response.isSuccessful()) {
                var body = response.body();
                if (body == null) {
                    throw new EdcException(format("Received empty response body when receiving endpoint data reference at uri: %s", endpoint));
                }
                return CompletableFuture.completedFuture(Result.success());
            } else {
                throw new EdcException(format("Received error code %s when transferring endpoint data reference at uri: %s", response.code(), endpoint));
            }
        }
    }
```

## Possible Implementation

I'd start with debugging the `TransferProcessManagerImpl` on provider side.

**Update & Possible Workaround:**
For everybody who is interested. If I read our logs correct, the issue was in our case a redirect done by the data plane. We solved it by changing the public API URL of the data plane, in the control plane settings from `http://dataplane:8185/api/public` to `http://dataplane:8185/api/public/`.

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by DrDanielMetz** [comment] 2022-10-04 10:05
We are seeing the same behaviour on a provider EDC and backend application.

On the provider side I am stopping this by cancelling the transfer process (below an example) with
`HTTP POST .../data/transferprocess/d1f1ace5-a2b9-4501-8f7d-cb9725d062d8/cancel`

`[2022-10-04 06:40:16] [SEVERE ] Error processing transfer request. Setting to retry: d1f1ace5-a2b9-4501-8f7d-cb9725d062d8
[2022-10-04 06:40:37] [FINE   ] Cancelling TransferProcess with ID d1f1ace5-a2b9-4501-8f7d-cb9725d062d8
[2022-10-04 06:40:37] [FINE   ] Transfer process canceled d1f1ace5-a2b9-4501-8f7d-cb9725d062d8
[2022-10-04 06:40:47] [SEVERE ] Error processing transfer request. Setting to retry: d1f1ace5-a2b9-4501-8f7d-cb9725d062d8
[2022-10-04 06:40:47] [FINE   ] Successfully processed command [class org.eclipse.dataspaceconnector.spi.types.domain.transfer.command.CancelTransferCommand]`

On the consumer backend service I constantly received new tokens:
`DEBUG 2022-10-04T08:04:12.269227322 Endpoint Data Reference received and cached for agreement: qualityinvestigationnotification-receipt-cd:83770d36-d872-49f3-94f7-b9d868c5efd7`

The reason why the transfer failed is unclear to me (at the moment) and the reason is not the error described by @DominikPinsel. Whatever the reason might be, I agree to the expected behaviour described above by @DominikPinsel.

**Comment by ndr-brt** [comment] 2022-11-04 10:49
This should have been already fixed:
- issue: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1954
- PR: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/1955

@DrDanielMetz since your problem seems to be a different one, could you open another issue? I would close this

**Closed by ndr-brt** 2022-11-04 10:49 UTC
Labels: bug
