### ISSUE TITLE
InMemoryCacheQueryAdapterRegistry and fcc-query-adapter-registry-memory are misleadingly named

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-dataspaceconnector/DataSpaceConnector#242] opened 2021-11-16 08:47 UTC
Hello everyone,

I found something strange in the fcc memory store extensions and I assume it hints to some kind of implementation error.
The two extensions in question are
- fcc-store-memory
- fcc-query-adapter-registry-memory

The **fcc-store-memory** extension has a storage class that implements the `FederatedCacheStore` interface. It looks like this:
```java
public class InMemoryFederatedCacheStore implements FederatedCacheStore {
        // content
}
```

The **fcc-query-adapter-registry-memory** extension has a storage class that stores implementations of the `CacheQueryAdapter` interface. The default implementation of this interface is the `DefaultCacheQueryAdapter` and looks like this:
```java
public class DefaultCacheQueryAdapter implements CacheQueryAdapter {

    private final FederatedCacheStore store;

    public DefaultCacheQueryAdapter(FederatedCacheStore store) {
        this.store = store;
    }
  
   // content
}
```

I assume it's an implementation error that one stored class contains another store.

**Comment by paullatzelsperger** [comment] 2021-11-16 13:24
Are you suggesting eliminating the `FederatedCacheStore`?

**Comment by DominikPinsel** [comment] 2021-11-16 14:03
I'm not sure as I don't know the implementation that well and haven't looked at the whole fcc code. But in case we don't need this extra store, because the `FederatedCachedStore` is already persisted by the stored `CacheQueryAdapter` I'd say we can delete it.
But again, I don't know the code and cannot say whether this is a solution. I just saw that one object is stored twice, what hints that  some kind of error happened.

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by paullatzelsperger** [comment] 2021-11-18 06:19
Maybe I don't understand the problem... This is how it was intended:

The `FederatedCacheStore` is the object that actually holds cached assets (i.e. a snapshot of the catalog) whereas the `CacheQueryAdapter` is a responsible for querying the store, it does not persist anything. Also, the `CacheQueryAdapter` itself is not stored (except in the `CacheQueryAdapterRegistry`).

Cached assets are persisted/stored by the `LoaderManager` and ultimately a `Loader`.

Could you point me to the exact locations where the `FederatedCacheStore` is persisted?

**Comment by jimmarino** [comment] 2021-11-19 06:47
I don't see any problem with this code. I'm going to close this issue out.

**Comment by DominikPinsel** [comment] 2021-11-19 20:23
Ok, maybe I need to explain myself better/shorter.

1. We have a registry/store for `CacheQueryAdapter` interface. 
2. The default implementation of this adapter holds another store in it's properties, like the `AssetIndex`. But in this case, it's called `FederatedCacheStore`.

As I would try to avoid storing the `AssetIndex` in some kind of other store, I assume this is also true for the `FederatedCacheStore`.

**Comment by paullatzelsperger** [comment] 2021-11-19 21:47
The assetindex is fundamentally different from the federated cache store.

**Comment by jimmarino** [comment] 2021-11-19 22:03
I don't understand what the issue is. By definition, the CacheQueryAdapter adds a custom query language over the backing store. AssetIndex is not a query adaptor, it is an index of assets. 

This approach makes sense to me.

**Comment by DominikPinsel** [comment] 2021-11-19 22:18
@paullatzelsperger 
> The assetindex is fundamentally different from the federated cache store.

That's true. I just thought the `AsserIndex` might be a good example, as it's well known and both classes may store a large amount of `Asset`. 

@jimmarino 
> I don't understand what the issue is. By definition, the CacheQueryAdapter adds a 
> custom query language over the backing store. AssetIndex is not a query adaptor, it is > an index of assets.
>
> This approach makes sense to me.

That's true, but I think it's still missing my point. 

Maybe another approach:
The default implementation of the `CacheQueryAdapter` contains the `FederatedCacheStore` as property. Every time one `CacheQueryAdapter` gets stored, all the catalogs from all other connectors are stored with it.

And this is, what looks like an implementation error. Because the catalogs are already stored in the `FederatedCacheStore` and it makes the size of one `CacheQueryAdapter` incredible big.

Again, maybe I didn't understand something in the code. But hopefully you now get my point. I just assume, all the catalogs should not be stored with the `CacheQueryAdapter`.

**Comment by DominikPinsel** [comment] 2021-11-19 22:29
> Maybe I don't understand the problem... This is how it was intended:
> 
> The `FederatedCacheStore` is the object that actually holds cached assets (i.e. a snapshot of the catalog) whereas the `CacheQueryAdapter` is a responsible for querying the store, it does not persist anything. Also, the `CacheQueryAdapter` itself is not stored (except in the `CacheQueryAdapterRegistry`).
> 
> Cached assets are persisted/stored by the `LoaderManager` and ultimately a `Loader`.
> 
> Could you point me to the exact locations where the `FederatedCacheStore` is persisted?

The `FederatedCacheStore` is stored by the `CacheQueryAdapterRegistry`. This is possible, because the default implementation if the `FederatedCacheStore` (`DefaultCacheQueryAdapter`) has the `FederatedCacheStore` as field.

**Comment by jimmarino** [comment] 2021-11-19 22:50
I still don't follow. My understanding is the `CacheQueryAdapterRegistry` registers and dispatches to  `CacheQueryAdapter`s. It's not intended (at least as far as I can tell) to serialize or persist anything. It is just a query facade for a backing store.

@paullatzelsperger is that accurate?

**Comment by DominikPinsel** [comment] 2021-11-19 22:57
@jimmarino Maybe then the 'in-memory' extension thing is confusing me. So there is no need to create an extra in-memory extension for this, as there is just no other way than to store it than in memory?
For me the extension, as it only has a `ServiceExtension` and `AdapterRegistry` class, looked like an extension point for the future.

**Comment by jimmarino** [comment] 2021-11-20 14:17
The name could be confusing @paullatzelsperger should it be just an Impl?

**Comment by paullatzelsperger** [comment] 2021-11-20 14:22
Yes, seems plausible.

**Comment by jimmarino** [comment] 2021-11-20 23:13
@paullatzelsperger I changed the name of the issue to reflect what this issue is highlighting. Can you think of a better name, maybe something with a simple "impl"?

**Comment by paullatzelsperger** [comment] 2021-11-21 07:16
If we do this, we do this properly and also move/rename the `InMemoryCatalogQueryAdapterRegistry`

**Comment by DominikPinsel** [comment] 2021-11-21 13:05
Thanks, I think I now understand the code a little better. Thank you two for explaining it to me :) even when it took a while!

**Closed** 2022-01-14 10:37 UTC
