### ISSUE TITLE
javadoc breaking on html table tags in Comments

### ISSUE THREAD

**Issue by chrislomonico** [eclipse-dataspaceconnector/DataSpaceConnector#1691] opened 2022-07-14 10:06 UTC
# Bug Report

## Describe the Bug

PR #1657 introduced an HTML table in [ServiceResultHandler.java](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/extensions/api/api-core/src/main/java/org/eclipse/dataspaceconnector/api/ServiceResultHandler.java).
`javadoc` breaks on this format of the table. 

### Expected Behavior
`javadoc` task is able to complete as expected without exception

### Observed Behavior
`javadoc` task is throwing the following exceptions:

```
error: tag not allowed here: <th>
  *   <th>reason</th>
error: tag not allowed here: <th>
  *   <th>exception</th>
no summary or caption for table
     * </table>
```

## Steps to Reproduce
1. create a branch from current  `main` (or use `main`)
2. run ```./gradlew publishToMavenLocal -Pskip.signing```
3. See exceptions

## Context Information

- Used version [e.g. EDC v1.0.0]
- OS: Windows 11

## Possible Implementation
Simple fix to add `caption` tag and change `th` tags out

**Comment by paullatzelsperger** [comment] 2022-07-18 05:56
duplicate of #1700

**Closed** 2022-07-19 05:50 UTC
Labels: bug
